name: ci cd for todo app
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
  pull_request:
    types: [opened]
    branches:
      - staging
jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install libraries and packages
        run: npm install
      - name: run code linter
        run: npm run lint
      - name: run unit test
        run: npm run test
      - name: run e2e test
        run: npm run test:e2e
  build_app:
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install libraries and packages
        run: npm install
      - name: build application
        run: npm run build
