name: ci cd for todo app
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
  pull_request:
    types: [opened]
    branches:
      - staging
jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install libraries and packages
        run: npm install
      - name: run code linter
        run: npm run lint
      - name: run unit test
        run: npm run test
      - name: run e2e test
        run: npm run test:e2e
  build_app:
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install libraries and packages
        run: npm install
      - name: build application
        run: npm run build
  deploy_evennode:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EVENNODE_SSH_KEY }}
        known_hosts: " "
    - name: Add git.evennode.com to known_hosts
      run: |
        ssh-keyscan -H git.evennode.com > ~/.ssh/known_hosts
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to evennode.com
      run: |
        git remote add evennode ${{ secrets.EVENNODE_REPO_URL }}
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
        git push evennode +master
